# Generated by Django 3.0.3 on 2020-03-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_post_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetooneprofile',
            name='image_url',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
