# Generated by Django 3.0.3 on 2020-03-21 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200321_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='fk_post_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Post'),
        ),
    ]
