# Generated by Django 3.0.3 on 2020-03-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200321_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
